name: carbonplan
channels:
  - conda-forge
dependencies:
  - aiohttp
  - altair
  - cartopy
  - fsspec
  - geopandas
  - geoviews
  - hvplot
  - intake
  - intake-geopandas
  - jupyterlab
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pydap
  - pyproj
  - pystan
  - requests
  - seaborn
  - shapely
  - xarray
  - xlrd
  - pip
  - pip:
      - carbonplan[styles,data]
