name: carbonplan
channels:
  - conda-forge
dependencies:
  - aiohttp
  - altair
  - fsspec
  - geopandas
  - hvplot
  - intake
  - intake-geopandas
  - matplotlib
  - numpy
  - pandas
  - pyproj
  - pystan
  - requests
  - shapely
  - xlrd
  - pip
  - pip:
      - carbonplan[styles,data]
