name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: master

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: '*'
          channels: conda-forge
          environment-file: binder/environment.yml
          python-version: ${{ matrix.python-version }}
          activate-environment: carbonplan
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - shell: bash -l {0}
        run: |
          python -m pip install nbconvert
          python -m pip list
      - shell: bash -l {0}
        name: Running Tests
        run: |
          for nb in **/*.ipynb; do echo $nb; time jupyter nbconvert --to notebook --execute $nb; done

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2.3.1
      - uses: pre-commit/action@v2.0.3
